on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.8", "1.12", "1.13", "1.14", "1.x"]
        # Doesn't work on Linux.
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        # -d prevents installation, which fails for Go 1.8 on macOS
        run: go get -d -t -v ./... && go test -v ./...
